#ifndef __TARANG_VERSION_H__
#define __TARANG_VERSION_H__

#define TARANG_VERSION_MAJOR 0
#define TARANG_VERSION_MINOR 1
#define TARANG_VERSION_PATCH 0

#define STRINGIFY(x) #x
#define TOSTRING(x) STRINGIFY(x)

#define CONCATENATE_VERSION(major, minor, patch) TOSTRING(major) "." TOSTRING(minor) "." TOSTRING(patch)
#define TARANG_VERSION_STRING CONCATENATE_VERSION(TARANG_VERSION_MAJOR, TARANG_VERSION_MINOR, TARANG_VERSION_PATCH)

#endif /* __TARANG_VERSION_H__ */
